<?php
// $Id$

/**
 * @file
 *
 * Contains install and uninstall functions
 *
 * @author Dustin Currie <dustinc@getlevelten.com>
 */

/**
 * Implementation of hook_uninstall().
 */

function uncaptchalous_uninstall() {
  variable_del('uncaptchalous_honeypot_field_title');
  variable_del('uncaptchalous_javascript');
  variable_del('uncaptchalous_honeypot_field');
  variable_del('uncaptchalous_visibility');
  variable_del('uncaptchalous_form_ids');
}